### POST
POST http://localhost:8080/match
Content-Type: application/json

{
  "round": 1,
  "homeTeam": "Corinthians",
  "awayTeam": "Santos",
  "matchDate": "2025-10-10"
}

### PUT

PUT http://localhost:8080/match/6844510c90130bdbeffe0055/score
Content-Type: application/json

{
  "homeTeam": 0,
  "awayTeam": 2
}

### GET Find by round
GET http://localhost:8080/match/round/5


