### POST
POST http://localhost:8080/match
Content-Type: application/json

{
  "round": 1,
  "homeTeam": "Corinthians",
  "awayTeam": "Santos",
  "matchDate": "2025-10-10",
  "status": "Open"
}

### PUT

PUT http://localhost:8080/match/68473dc4692a72b3ee63a1ca/score
Content-Type: application/json

{
  "homeTeam": 4,
  "awayTeam": 2
}

### GET Find by username and round
GET http://localhost:8080/match/ricas/round/5

### Close all matches and return total
GET http://localhost:8080/match/close

